CREATE TABLE `videos` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `channelName` VARCHAR(255) NOT NULL,
  `viewersNum` INT NOT NULL,
  `live` BOOLEAN NOT NULL,
  `src` VARCHAR(255) NOT NULL
);

INSERT INTO `videos` (`title`, `channelName`, `viewersNum`, `live`, `src`) VALUES
('Let’s Build - GamerZone', 'GamerZone', 31802, 1, '/thumbnails/thumbnail.jpg'),
('Life Lessons - GamerZone', 'GamerZone', 58764, 1, '/thumbnails/thumbnail.jpg'),
('Around The World - GamerZone', 'GamerZone', 31312, 1, '/thumbnails/thumbnail.jpg'),
('Tech Talk - SpeedyRunners', 'SpeedyRunners', 73271, 1, '/thumbnails/thumbnail.jpg'),
('Daily Recap - SpeedyRunners', 'SpeedyRunners', 18638, 1, '/thumbnails/thumbnail.jpg'),
('New Discovery - SpeedyRunners', 'SpeedyRunners', 9585, 0, '/thumbnails/thumbnail.jpg'),
('Around The World - SpeedyRunners', 'SpeedyRunners', 80185, 0, '/thumbnails/thumbnail.jpg'),
('Vlog Day - SpeedyRunners', 'SpeedyRunners', 80367, 1, '/thumbnails/thumbnail.jpg'),
('Around The World - DocuWorld', 'DocuWorld', 23795, 0, '/thumbnails/thumbnail.jpg'),
('Ultimate Challenge - DocuWorld', 'DocuWorld', 60938, 1, '/thumbnails/thumbnail.jpg'),
('Time Travel - DocuWorld', 'DocuWorld', 40681, 1, '/thumbnails/thumbnail.jpg'),
('Tech Talk - DocuWorld', 'DocuWorld', 29577, 1, '/thumbnails/thumbnail.jpg'),
('Speedrun Secrets - DocuWorld', 'DocuWorld', 20017, 1, '/thumbnails/thumbnail.jpg'),
('New Discovery - Cooking Craze', 'Cooking Craze', 17031, 0, '/thumbnails/thumbnail.jpg'),
('Top Moments - Cooking Craze', 'Cooking Craze', 12272, 1, '/thumbnails/thumbnail.jpg'),
('Mastering Skills - Cooking Craze', 'Cooking Craze', 46052, 0, '/thumbnails/thumbnail.jpg'),
('Life Lessons - Cooking Craze', 'Cooking Craze', 78996, 0, '/thumbnails/thumbnail.jpg'),
('Science Uncovered - Unbox Therapy', 'Unbox Therapy', 5196, 0, '/thumbnails/thumbnail.jpg'),
('Speedrun Secrets - Unbox Therapy', 'Unbox Therapy', 8960, 1, '/thumbnails/thumbnail.jpg'),
('Docu Series - Unbox Therapy', 'Unbox Therapy', 6615, 1, '/thumbnails/thumbnail.jpg'),
('Behind The Scenes - Unbox Therapy', 'Unbox Therapy', 83555, 0, '/thumbnails/thumbnail.jpg'),
('Live Battle - Unbox Therapy', 'Unbox Therapy', 53977, 0, '/thumbnails/thumbnail.jpg'),
('Around The World - MusicMania', 'MusicMania', 69044, 0, '/thumbnails/thumbnail.jpg'),
('Speedrun Secrets - MusicMania', 'MusicMania', 13682, 1, '/thumbnails/thumbnail.jpg'),
('Docu Series - MusicMania', 'MusicMania', 62813, 1, '/thumbnails/thumbnail.jpg'),
('Behind The Scenes - MusicMania', 'MusicMania', 49604, 1, '/thumbnails/thumbnail.jpg'),
('Science Uncovered - SciTech Daily', 'SciTech Daily', 84918, 1, '/thumbnails/thumbnail.jpg'),
('Docu Series - SciTech Daily', 'SciTech Daily', 5194, 1, '/thumbnails/thumbnail.jpg'),
('Time Travel - SciTech Daily', 'SciTech Daily', 85065, 0, '/thumbnails/thumbnail.jpg'),
('Flashback - SciTech Daily', 'SciTech Daily', 17497, 1, '/thumbnails/thumbnail.jpg'),
('Tech Talk - SciTech Daily', 'SciTech Daily', 40353, 0, '/thumbnails/thumbnail.jpg'),
('Let’s Build - SciTech Daily', 'SciTech Daily', 27076, 0, '/thumbnails/thumbnail.jpg'),
('Top Moments - SciTech Daily', 'SciTech Daily', 70964, 0, '/thumbnails/thumbnail.jpg'),
('Amazing Tricks - SciTech Daily', 'SciTech Daily', 5954, 1, '/thumbnails/thumbnail.jpg'),
('Ultimate Challenge - World Explorers', 'World Explorers', 64075, 0, '/thumbnails/thumbnail.jpg'),
('Behind The Scenes - World Explorers', 'World Explorers', 34497, 1, '/thumbnails/thumbnail.jpg'),
('Life Lessons - World Explorers', 'World Explorers', 12380, 1, '/thumbnails/thumbnail.jpg'),
('Speedrun Secrets - World Explorers', 'World Explorers', 20840, 0, '/thumbnails/thumbnail.jpg'),
('New Discovery - World Explorers', 'World Explorers', 16142, 1, '/thumbnails/thumbnail.jpg'),
('Let’s Build - World Explorers', 'World Explorers', 66986, 0, '/thumbnails/thumbnail.jpg'),
('Time Travel - World Explorers', 'World Explorers', 36285, 1, '/thumbnails/thumbnail.jpg'),
('Amazing Tricks - World Explorers', 'World Explorers', 87506, 0, '/thumbnails/thumbnail.jpg'),
('Tech Talk - NextGen Coders', 'NextGen Coders', 21522, 0, '/thumbnails/thumbnail.jpg'),
('Top Moments - NextGen Coders', 'NextGen Coders', 42287, 1, '/thumbnails/thumbnail.jpg'),
('Time Travel - NextGen Coders', 'NextGen Coders', 39393, 1, '/thumbnails/thumbnail.jpg'),
('Speedrun Secrets - NextGen Coders', 'NextGen Coders', 53294, 1, '/thumbnails/thumbnail.jpg'),
('Flashback - Epic Creators', 'Epic Creators', 78188, 1, '/thumbnails/thumbnail.jpg'),
('Let’s Build - Epic Creators', 'Epic Creators', 77471, 0, '/thumbnails/thumbnail.jpg'),
('Top Moments - Epic Creators', 'Epic Creators', 8232, 0, '/thumbnails/thumbnail.jpg'),
('Time Travel - Epic Creators', 'Epic Creators', 14267, 1, '/thumbnails/thumbnail.jpg'),
('Cooking Hacks - Epic Creators', 'Epic Creators', 51312, 1, '/thumbnails/thumbnail.jpg'),
('Amazing Tricks - Epic Creators', 'Epic Creators', 57848, 0, '/thumbnails/thumbnail.jpg'),
('Live Battle - Epic Creators', 'Epic Creators', 44542, 1, '/thumbnails/thumbnail.jpg'),
('Mastering Skills - Ultimate Builders', 'Ultimate Builders', 1357, 0, '/thumbnails/thumbnail.jpg'),
('Let’s Build - Ultimate Builders', 'Ultimate Builders', 12795, 0, '/thumbnails/thumbnail.jpg'),
('Vlog Day - Ultimate Builders', 'Ultimate Builders', 79707, 1, '/thumbnails/thumbnail.jpg'),
('Around The World - Ultimate Builders', 'Ultimate Builders', 44242, 0, '/thumbnails/thumbnail.jpg'),
('New Discovery - Ultimate Builders', 'Ultimate Builders', 37650, 0, '/thumbnails/thumbnail.jpg'),
('Top Moments - History Buffs', 'History Buffs', 27562, 1, '/thumbnails/thumbnail.jpg'),
('Live Battle - History Buffs', 'History Buffs', 56460, 1, '/thumbnails/thumbnail.jpg'),
('Tech Talk - History Buffs', 'History Buffs', 22233, 0, '/thumbnails/thumbnail.jpg'),
('Ultimate Challenge - History Buffs', 'History Buffs', 70630, 1, '/thumbnails/thumbnail.jpg'),
('Around The World - History Buffs', 'History Buffs', 52486, 1, '/thumbnails/thumbnail.jpg'),
('Flashback - BehindTheCam', 'BehindTheCam', 3262, 1, '/thumbnails/thumbnail.jpg'),
('Around The World - BehindTheCam', 'BehindTheCam', 19537, 0, '/thumbnails/thumbnail.jpg'),
('Epic Gameplay - BehindTheCam', 'BehindTheCam', 37929, 0, '/thumbnails/thumbnail.jpg'),
('Cooking Hacks - Real Facts', 'Real Facts', 75890, 1, '/thumbnails/thumbnail.jpg'),
('Mastering Skills - Real Facts', 'Real Facts', 68512, 0, '/thumbnails/thumbnail.jpg'),
('Tech Talk - Real Facts', 'Real Facts', 86168, 1, '/thumbnails/thumbnail.jpg'),
('New Discovery - Real Facts', 'Real Facts', 86939, 0, '/thumbnails/thumbnail.jpg'),
('Amazing Tricks - Real Facts', 'Real Facts', 38452, 1, '/thumbnails/thumbnail.jpg'),
('Speedrun Secrets - Real Facts', 'Real Facts', 69990, 0, '/thumbnails/thumbnail.jpg'),
('Epic Gameplay - Daily Dose', 'Daily Dose', 50745, 0, '/thumbnails/thumbnail.jpg'),
('Vlog Day - Daily Dose', 'Daily Dose', 26915, 0, '/thumbnails/thumbnail.jpg'),
('New Discovery - Daily Dose', 'Daily Dose', 34855, 0, '/thumbnails/thumbnail.jpg'),
('Life Lessons - Challenge Squad', 'Challenge Squad', 83086, 1, '/thumbnails/thumbnail.jpg'),
('Live Battle - Challenge Squad', 'Challenge Squad', 76303, 1, '/thumbnails/thumbnail.jpg'),
('Around The World - Challenge Squad', 'Challenge Squad', 33109, 0, '/thumbnails/thumbnail.jpg'),
('Daily Recap - Challenge Squad', 'Challenge Squad', 36066, 0, '/thumbnails/thumbnail.jpg'),
('New Discovery - Challenge Squad', 'Challenge Squad', 76825, 0, '/thumbnails/thumbnail.jpg'),
('Live Battle - Life Hacks', 'Life Hacks', 76822, 1, '/thumbnails/thumbnail.jpg'),
('New Discovery - Life Hacks', 'Life Hacks', 48342, 1, '/thumbnails/thumbnail.jpg'),
('Time Travel - Life Hacks', 'Life Hacks', 53622, 1, '/thumbnails/thumbnail.jpg'),
('Daily Recap - Life Hacks', 'Life Hacks', 5537, 0, '/thumbnails/thumbnail.jpg'),
('Ultimate Challenge - Life Hacks', 'Life Hacks', 45667, 1, '/thumbnails/thumbnail.jpg'),
('Behind The Scenes - Life Hacks', 'Life Hacks', 4589, 1, '/thumbnails/thumbnail.jpg'),
('Daily Recap - Retro Revival', 'Retro Revival', 35047, 1, '/thumbnails/thumbnail.jpg'),
('Cooking Hacks - Retro Revival', 'Retro Revival', 12512, 0, '/thumbnails/thumbnail.jpg'),
('Docu Series - Retro Revival', 'Retro Revival', 44304, 0, '/thumbnails/thumbnail.jpg'),
('Tech Talk - Retro Revival', 'Retro Revival', 85013, 1, '/thumbnails/thumbnail.jpg'),
('Flashback - Retro Revival', 'Retro Revival', 32570, 1, '/thumbnails/thumbnail.jpg'),
('Amazing Tricks - Retro Revival', 'Retro Revival', 42164, 1, '/thumbnails/thumbnail.jpg'),
('Vlog Day - The Chill Stream', 'The Chill Stream', 56131, 0, '/thumbnails/thumbnail.jpg'),
('Speedrun Secrets - The Chill Stream', 'The Chill Stream', 11850, 0, '/thumbnails/thumbnail.jpg'),
('Life Lessons - The Chill Stream', 'The Chill Stream', 15926, 1, '/thumbnails/thumbnail.jpg'),
('Flashback - The Chill Stream', 'The Chill Stream', 87903, 0, '/thumbnails/thumbnail.jpg'),
('Docu Series - The Chill Stream', 'The Chill Stream', 9675, 1, '/thumbnails/thumbnail.jpg'),
('Time Travel - The Chill Stream', 'The Chill Stream', 50823, 1, '/thumbnails/thumbnail.jpg'),
('Cooking Hacks - The Chill Stream', 'The Chill Stream', 69159, 0, '/thumbnails/thumbnail.jpg'),
('Epic Gameplay - The Chill Stream', 'The Chill Stream', 81851, 1, '/thumbnails/thumbnail.jpg');




CREATE TABLE `subscriptions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `channelName` VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO `subscriptions` (`channelName`) VALUES
('GamerZone'),
('SpeedyRunners'),
('DocuWorld'),
('Cooking Craze'),
('Unbox Therapy'),
('MusicMania'),
('SciTech Daily'),
('World Explorers'),
('NextGen Coders'),
('Epic Creators'),
('Ultimate Builders'),
('History Buffs'),
('BehindTheCam'),
('Real Facts'),
('Daily Dose'),
('Challenge Squad'),
('Life Hacks'),
('Retro Revival'),
('The Chill Stream');